### ISSUE TITLE
Scope for catcode changes

### ISSUE THREAD

**Issue by Aerijo** [yitzchak/tree-sitter-latex#30]
I don't have experience with this myself, but [catcode changes are group local](https://tex.stackexchange.com/questions/33465/changing-the-catcode-of-in-one-command/33470). This means that we'd need a very complicated system to track changes (and be able to serialise it), or wipe the changes after an end group token.

E.g., how would it handle
```latex
\catcode`\%=12 { \catcode`\%=9 { \catcode`\%=11 } \catcode`\%=12 } 
```
At the very least it'd need a stack for all catcodes, along with the group they were defined in.

I very much feel that sticking with common shifts like `ExplSyntaxOn` is still fine, but arbitrary handling just cannot work. and adds unnecessary complexity to the parser.

(Sorry if this sounds negative, but it's a fundamental design choice. Also sorry for inactivity recently, been doing various other things including setting up `tree-sitter-biber` support to be released at the same time as we add this. I'm going to go all in with a version 2.0 of `language-latex`)

**Comment by yitzchak** [comment]
I agree that attempting to keep track of group local behavior will definitely be difficult and may not be worth it. I introduced the zero width scanner symbol `_CS_END` which has moved significant complexity out of the external scanner. If we ever want to explore group local settings I don't think it will impact `grammar.js` significantly. At the same time, I don't think this is a high priority yet, but something to think  about for the future.

In regards to `tree-sitter-biber` have you considered doing injections of `source.latex` into `value`? Just a thought.

And no worries about inactivity. We all have stuff going on. :smile:

**Comment by Aerijo** [comment]
> have you considered doing injections of source.latex into value? 

I hadn't considered it; at the level biber reads it, it's just a string of characters.

It does seem reasonable though, expecially if it is passed straight to LaTeX. And it's relatively safe too, as Tree-sitter doesn't leak embedded languages. 

(Interestingly, TextMate grammars really only leak because the TextMate editor itself does this, and maintainers are prioritising matching behaviour over fixing the buggy behaviour. It's an unfortunate situation, but should hopefully be a small issue when grammars like GFM get Tree-sitter versions.)

**Comment by yitzchak** [comment]
@Aerijo Thank you for your thoughts and feedback. I completely understand if you think the grammar is headed in the wrong direction and do not wish to invest time into contributing because of that. In defense of the current state please consider the following arguments.

I believe that the external scanner is probably done minus some optimizations. The benchmarking that I have done so far seems to indicate that catcode scanning isn't  currently adding a lot of time to parsing. Instead what seems to really hang tree-sitter up are errors which should be eased by #39. In other words, the remainder of the work to be done is in the actual `grammar.js` defining commands and syntax. 

In general, we have to decide on the level incompleteness we will be satisfied with because  [TeX is Turing complete and context sensitive](https://tex.stackexchange.com/questions/4201/is-there-a-bnf-grammar-of-the-tex-language/4205#4205).

Also, I am certainly willing to explore limited catcode scanning, BTW. I don't think that the current state precludes that.

I hope you still want to pitch in, but I understand either way.
