### ISSUE TITLE
Allowing for incomplete commands

### ISSUE THREAD

**Issue by yitzchak** [yitzchak/tree-sitter-latex#39]
Currently the absence of required parameters in a command causes an error. For example, `\foo{\textbf}` parses as

```
(document [0, 0] - [1, 0]
  (cs [0, 0] - [0, 4])
  (ERROR [0, 4] - [1, 0]
    (l [0, 4] - [0, 5])
    (cs [0, 5] - [0, 12])
    (verb_delim [0, 12] - [0, 13])))
```

If the enclosing command is known to have control sequences as parameters this can be accounted for. For instance, `\def\textbf{\foo}` parses as

```
(document [0, 0] - [1, 0]
  (storage [0, 0] - [0, 17]
    (cs [0, 0] - [0, 4])
    (cs [0, 4] - [0, 11])
    (group [0, 11] - [0, 17]
      (l [0, 11] - [0, 12])
      (cs [0, 12] - [0, 16])
      (r [0, 16] - [0, 17])))
  (text [0, 17] - [1, 0]))
```

Since it is probably impossible to anticipate all commands that have control sequences as parameters this will have to be accounted for in the grammar.

**Comment by Aerijo** [comment]
@yitzchak Yes, I think we need to relax the requirements. 

Tangentially, something I've been wanting to try ever since writing my first grammar is
- For "standard" commands, grab as many as we can that we know it should have
- For arbitrary commands, consider all immediately following sets of braces to be arguments

E.g., `\foo{bar}{baz} hello {world}` would be considered a command `foo` that takes two arguments. This approximation could be handled on the other side (i.e., the program interpreting the tree), but this way it lets users scope arguments differently.

Something I'm not sure on is whether to require no spaces between them. So `\foo{bar}` definitely has an argument, but what about `\foo {bar}`? Would also need to consider with optional arguments; `\foo[bar]`, `\foo[bar]{baz}`, `\foo{bar}[baz]`, etc.

I feel this would work fine if the user knows what's happening and writes with it in mind, but it may be less useful for parsing arbitrary documents written by ~~crazy~~ inspired people.
